apiVersion: apps/v1
kind: Deployment
metadata:
  name: workspace-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: workspace-service
  template:
    metadata:
      labels:
        app: workspace-service
    spec:
      containers:
        - name: workspace-service
          image: rangein-task-system-workspace-service:dev
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: rangein-config
            - secretRef:
                name: rangein-secret
